#!/usr/bin/env python3
# ruff: noqa: E501
"""Fetch pycollege/python-by-example into the playground example data file."""

from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path
from typing import Any

REPO = "pycollege/python-by-example"
BRANCH = "main"
API = f"https://api.github.com/repos/{REPO}/contents"
RAW = f"https://raw.githubusercontent.com/{REPO}/{BRANCH}"
OUT = Path("examples/experimental/python-by-example-playground/src/examples_data.py")


def fetch_json(url: str) -> Any:
    with urllib.request.urlopen(url, timeout=30) as response:
        return json.load(response)


def fetch_text(url: str) -> str:
    with urllib.request.urlopen(url, timeout=30) as response:
        return response.read().decode("utf-8")


def title_from_lesson(markdown: str, slug: str) -> str:
    match = re.search(r"^#\s+Python by Example:\s*(.+)$", markdown, re.M)
    if match:
        return match.group(1).strip()
    return slug.replace("-", " ").title()


def summary_from_lesson(markdown: str) -> str:
    paragraphs: list[str] = []
    in_fence = False
    for line in markdown.splitlines():
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence or line.startswith("#") or line.startswith("**"):
            continue
        stripped = line.strip()
        if stripped and not stripped.startswith(("-", "*", "Source:", "Next:", "Previous:")):
            paragraphs.append(stripped)
        if paragraphs:
            break
    return paragraphs[0] if paragraphs else "Runnable Python example."


def main() -> None:
    sources = [item for item in fetch_json(f"{API}/source") if item["name"].endswith(".py")]
    examples: list[dict[str, str]] = []
    for item in sorted(sources, key=lambda x: x["name"]):
        name = item["name"]
        slug = name[:-3]
        source = fetch_text(f"{RAW}/source/{name}")
        lesson_name = "json.md" if slug == "json-example" else f"{slug}.md"
        try:
            lesson = fetch_text(f"{RAW}/lessons/{lesson_name}")
        except Exception:
            lesson = f"# Python by Example: {slug.replace('-', ' ').title()}\n\nRunnable Python example."
        examples.append(
            {
                "slug": slug,
                "title": title_from_lesson(lesson, slug),
                "summary": summary_from_lesson(lesson),
                "source_path": f"source/{name}",
                "lesson_path": f"lessons/{lesson_name}",
                "code": source,
            }
        )

    license_text = fetch_text(f"{RAW}/LICENSE")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "# ruff: noqa: E501\n"
        "# Generated by scripts/fetch_python_by_example.py.\n"
        "# Source: https://github.com/pycollege/python-by-example\n"
        "# License: Creative Commons Attribution 4.0 International.\n\n"
        f"SOURCE_REPOSITORY = {REPO!r}\n"
        f"SOURCE_URL = {'https://github.com/' + REPO!r}\n"
        "SOURCE_AUTHOR = 'Dariush Abbasi / pycollege'\n"
        "SOURCE_LICENSE = 'Creative Commons Attribution 4.0 International (CC BY 4.0)'\n"
        f"SOURCE_LICENSE_TEXT = {license_text!r}\n"
        f"EXAMPLES = {examples!r}\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} with {len(examples)} examples")


if __name__ == "__main__":
    main()
